#!/bin/bash

echo "================================"
echo "  Finton Text Editor - Demo"
echo "================================"
echo ""
echo "✓ Binary built: $(ls -lh finton | awk '{print $5}')"
echo "✓ Tests passing: $(go test ./... 2>&1 | grep -c PASS) tests"
echo "✓ Lines of code: $(find . -name "*.go" -type f -exec wc -l {} + | tail -1 | awk '{print $1}')"
echo ""
echo "Quick Start:"
echo "  1. Install: ./install.sh"
echo "  2. Run: finton test.txt"
echo ""
echo "Try these commands:"
echo "  finton test.txt           # Edit test file"
echo "  finton test_sample.json   # Edit JSON (try Ctrl+F to format)"
echo "  finton README.md          # View readme with markdown highlighting"
echo ""
echo "Key Features:"
echo "  • Ctrl+S - Save file"
echo "  • Ctrl+Q - Quit"
echo "  • Ctrl+H - Cycle themes (Dark/Light/Monokai/Solarized)"
echo "  • Ctrl+A - AI prompt (requires Ollama or OpenAI)"
echo "  • Ctrl+F - Format JSON"
echo "  • Ctrl+C/V/X - Copy/Paste/Cut"
echo ""
echo "AI Setup (optional):"
echo "  curl -fsSL https://ollama.com/install.sh | sh"
echo "  ollama pull llama3.2"
echo "  Edit ~/.finton.yaml and set ai.enabled: true"
echo ""
echo "================================"
